//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Starline.SmartNota.Util.NFSe.WS.SJC.PedidoEnvioRPS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PedidoEnvioRPS.cfcSoapBinding", Namespace="PedidoEnvioRPS")]
    public partial class PedidoEnvioRPSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetornoEnvioRPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback PedidoEnvioRPSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PedidoEnvioRPSService() {
            this.Url = global::Starline.SmartNota.Util.Properties.Settings.Default.SmartNota_Util_NFSe_WS_SJC_PedidoEnvioRPS_PedidoEnvioRPSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetornoEnvioRPSCompletedEventHandler RetornoEnvioRPSCompleted;
        
        /// <remarks/>
        public event PedidoEnvioRPSCompletedEventHandler PedidoEnvioRPSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="PedidoEnvioRPS", ResponseNamespace="PedidoEnvioRPS")]
        [return: System.Xml.Serialization.SoapElementAttribute("RetornoEnvioRPSReturn")]
        public string RetornoEnvioRPS(bool sucesso, double pid, double mobi, string NumeroRPS, string SerieRPS, string DocumentoPrestador, string InscricaoMunicipal, string DataEmissao, string DataConversao, string hashOperacao, string NumeroNFe) {
            object[] results = this.Invoke("RetornoEnvioRPS", new object[] {
                        sucesso,
                        pid,
                        mobi,
                        NumeroRPS,
                        SerieRPS,
                        DocumentoPrestador,
                        InscricaoMunicipal,
                        DataEmissao,
                        DataConversao,
                        hashOperacao,
                        NumeroNFe});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetornoEnvioRPSAsync(bool sucesso, double pid, double mobi, string NumeroRPS, string SerieRPS, string DocumentoPrestador, string InscricaoMunicipal, string DataEmissao, string DataConversao, string hashOperacao, string NumeroNFe) {
            this.RetornoEnvioRPSAsync(sucesso, pid, mobi, NumeroRPS, SerieRPS, DocumentoPrestador, InscricaoMunicipal, DataEmissao, DataConversao, hashOperacao, NumeroNFe, null);
        }
        
        /// <remarks/>
        public void RetornoEnvioRPSAsync(bool sucesso, double pid, double mobi, string NumeroRPS, string SerieRPS, string DocumentoPrestador, string InscricaoMunicipal, string DataEmissao, string DataConversao, string hashOperacao, string NumeroNFe, object userState) {
            if ((this.RetornoEnvioRPSOperationCompleted == null)) {
                this.RetornoEnvioRPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornoEnvioRPSOperationCompleted);
            }
            this.InvokeAsync("RetornoEnvioRPS", new object[] {
                        sucesso,
                        pid,
                        mobi,
                        NumeroRPS,
                        SerieRPS,
                        DocumentoPrestador,
                        InscricaoMunicipal,
                        DataEmissao,
                        DataConversao,
                        hashOperacao,
                        NumeroNFe}, this.RetornoEnvioRPSOperationCompleted, userState);
        }
        
        private void OnRetornoEnvioRPSOperationCompleted(object arg) {
            if ((this.RetornoEnvioRPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornoEnvioRPSCompleted(this, new RetornoEnvioRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="PedidoEnvioRPS", ResponseNamespace="PedidoEnvioRPS")]
        [return: System.Xml.Serialization.SoapElementAttribute("PedidoEnvioRPSReturn")]
        public string PedidoEnvioRPS(string username, string password, string xmlPedido) {
            object[] results = this.Invoke("PedidoEnvioRPS", new object[] {
                        username,
                        password,
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PedidoEnvioRPSAsync(string username, string password, string xmlPedido) {
            this.PedidoEnvioRPSAsync(username, password, xmlPedido, null);
        }
        
        /// <remarks/>
        public void PedidoEnvioRPSAsync(string username, string password, string xmlPedido, object userState) {
            if ((this.PedidoEnvioRPSOperationCompleted == null)) {
                this.PedidoEnvioRPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPedidoEnvioRPSOperationCompleted);
            }
            this.InvokeAsync("PedidoEnvioRPS", new object[] {
                        username,
                        password,
                        xmlPedido}, this.PedidoEnvioRPSOperationCompleted, userState);
        }
        
        private void OnPedidoEnvioRPSOperationCompleted(object arg) {
            if ((this.PedidoEnvioRPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PedidoEnvioRPSCompleted(this, new PedidoEnvioRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RetornoEnvioRPSCompletedEventHandler(object sender, RetornoEnvioRPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornoEnvioRPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornoEnvioRPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PedidoEnvioRPSCompletedEventHandler(object sender, PedidoEnvioRPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PedidoEnvioRPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PedidoEnvioRPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591