//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starline.SmartNota.Util.NFSe.WS.SJC.PedidoEnvioRPS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PedidoEnvioRPS", ConfigurationName="NFSe.WS.SJC.PedidoEnvioRPS.PedidoEnvioRPS")]
    public interface PedidoEnvioRPS {
        
        [System.ServiceModel.OperationContractAttribute()]
        void PedidoEnvioRPS();
        
        [System.ServiceModel.OperationContractAttribute()]
        void RetornoEnvioRPS();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoEnvioRPSChannel : Starline.SmartNota.Util.NFSe.WS.SJC.PedidoEnvioRPS.PedidoEnvioRPS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoEnvioRPSClient : System.ServiceModel.ClientBase<Starline.SmartNota.Util.NFSe.WS.SJC.PedidoEnvioRPS.PedidoEnvioRPS>, Starline.SmartNota.Util.NFSe.WS.SJC.PedidoEnvioRPS.PedidoEnvioRPS {
        
        public PedidoEnvioRPSClient() {
        }
        
        public PedidoEnvioRPSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoEnvioRPSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoEnvioRPSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoEnvioRPSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PedidoEnvioRPS() {
            base.Channel.PedidoEnvioRPS();
        }
        
        public void RetornoEnvioRPS() {
            base.Channel.RetornoEnvioRPS();
        }
    }
}
