//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Starline.SmartNota.Util.NFSe.WS.SJC.PedidoConsultaRPSNumero {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PedidoConsultaRPSNumero.cfcSoapBinding", Namespace="PedidoConsultaRPSNumero")]
    public partial class PedidoConsultaRPSNumeroService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PedidoConsultaRPSNumeroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PedidoConsultaRPSNumeroService() {
            this.Url = global::Starline.SmartNota.Util.Properties.Settings.Default.SmartNota_Util_NFSe_WS_SJC_PedidoConsultaRPSNumero_PedidoConsultaRPSNumeroService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PedidoConsultaRPSNumeroCompletedEventHandler PedidoConsultaRPSNumeroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="PedidoConsultaRPSNumero", ResponseNamespace="PedidoConsultaRPSNumero")]
        [return: System.Xml.Serialization.SoapElementAttribute("PedidoConsultaRPSNumeroReturn")]
        public string PedidoConsultaRPSNumero(string username, string password) {
            object[] results = this.Invoke("PedidoConsultaRPSNumero", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PedidoConsultaRPSNumeroAsync(string username, string password) {
            this.PedidoConsultaRPSNumeroAsync(username, password, null);
        }
        
        /// <remarks/>
        public void PedidoConsultaRPSNumeroAsync(string username, string password, object userState) {
            if ((this.PedidoConsultaRPSNumeroOperationCompleted == null)) {
                this.PedidoConsultaRPSNumeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPedidoConsultaRPSNumeroOperationCompleted);
            }
            this.InvokeAsync("PedidoConsultaRPSNumero", new object[] {
                        username,
                        password}, this.PedidoConsultaRPSNumeroOperationCompleted, userState);
        }
        
        private void OnPedidoConsultaRPSNumeroOperationCompleted(object arg) {
            if ((this.PedidoConsultaRPSNumeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PedidoConsultaRPSNumeroCompleted(this, new PedidoConsultaRPSNumeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PedidoConsultaRPSNumeroCompletedEventHandler(object sender, PedidoConsultaRPSNumeroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PedidoConsultaRPSNumeroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PedidoConsultaRPSNumeroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591